#############################################################################
# Makefile for building: MsgpackExample.app/Contents/MacOS/MsgpackExample
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  MsgpackExample.pro
# Template: app
# Command: /Users/gnufied/Qt/5.2.1/clang_64/bin/qmake -o Makefile MsgpackExample.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt/5.2.1/clang_64/mkspecs/macx-clang -I. -Imsgpack-c/include -I../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/gnufied/Qt/5.2.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/gnufied/Qt/5.2.1/clang_64/lib /Users/gnufied/qtapps/MsgpackExample/msgpack-c/lib/libmsgpack.a -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/gnufied/Qt/5.2.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf \
		MsgpackExample.pro \
		MsgpackExample.pro
QMAKE_TARGET  = MsgpackExample
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MsgpackExample.app/Contents/MacOS/MsgpackExample

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile MsgpackExample.app/Contents/PkgInfo MsgpackExample.app/Contents/Resources/empty.lproj MsgpackExample.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d MsgpackExample.app/Contents/MacOS/ || mkdir -p MsgpackExample.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MsgpackExample.pro ../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf \
		MsgpackExample.pro \
		/Users/gnufied/Qt/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/gnufied/Qt/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/gnufied/Qt/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile MsgpackExample.pro
../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri:
../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf:
../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf:
../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf:
../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.2.1/clang_64/mkspecs/common/clang.conf:
../../Qt/5.2.1/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/qt.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/resources.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/moc.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/uic.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf:
MsgpackExample.pro:
/Users/gnufied/Qt/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/gnufied/Qt/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/gnufied/Qt/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MsgpackExample.pro

qmake_all: FORCE

MsgpackExample.app/Contents/PkgInfo: 
	@test -d MsgpackExample.app/Contents || mkdir -p MsgpackExample.app/Contents
	@$(DEL_FILE) MsgpackExample.app/Contents/PkgInfo
	@echo "APPL????" >MsgpackExample.app/Contents/PkgInfo
MsgpackExample.app/Contents/Resources/empty.lproj: 
	@test -d MsgpackExample.app/Contents/Resources || mkdir -p MsgpackExample.app/Contents/Resources
	@touch MsgpackExample.app/Contents/Resources/empty.lproj
	
MsgpackExample.app/Contents/Info.plist: 
	@test -d MsgpackExample.app/Contents || mkdir -p MsgpackExample.app/Contents
	@$(DEL_FILE) MsgpackExample.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.MsgpackExample,g" -e "s,@EXECUTABLE@,MsgpackExample,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.2.1/clang_64/mkspecs/macx-clang/Info.plist.app >MsgpackExample.app/Contents/Info.plist
dist: 
	@test -d .tmp/MsgpackExample1.0.0 || mkdir -p .tmp/MsgpackExample1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MsgpackExample1.0.0/ && $(COPY_FILE) --parents mainwindow.h msgpack-c/include/msgpack.hpp .tmp/MsgpackExample1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/MsgpackExample1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/MsgpackExample1.0.0/ && (cd `dirname .tmp/MsgpackExample1.0.0` && $(TAR) MsgpackExample1.0.0.tar MsgpackExample1.0.0 && $(COMPRESS) MsgpackExample1.0.0.tar) && $(MOVE) `dirname .tmp/MsgpackExample1.0.0`/MsgpackExample1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MsgpackExample1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r MsgpackExample.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		mainwindow.h
	/Users/gnufied/Qt/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/gnufied/Qt/5.2.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		msgpack-c/include/msgpack.hpp \
		msgpack-c/include/msgpack/object.hpp \
		msgpack-c/include/msgpack/object.h \
		msgpack-c/include/msgpack/zone.h \
		msgpack-c/include/msgpack/sysdep.h \
		msgpack-c/include/msgpack/pack.hpp \
		msgpack-c/include/msgpack/pack_define.h \
		msgpack-c/include/msgpack/pack_template.h \
		msgpack-c/include/msgpack/zone.hpp \
		msgpack-c/include/msgpack/type.hpp \
		msgpack-c/include/msgpack/type/bool.hpp \
		msgpack-c/include/msgpack/type/deque.hpp \
		msgpack-c/include/msgpack/type/fixint.hpp \
		msgpack-c/include/msgpack/type/int.hpp \
		msgpack-c/include/msgpack/type/float.hpp \
		msgpack-c/include/msgpack/type/list.hpp \
		msgpack-c/include/msgpack/type/map.hpp \
		msgpack-c/include/msgpack/type/nil.hpp \
		msgpack-c/include/msgpack/type/pair.hpp \
		msgpack-c/include/msgpack/type/raw.hpp \
		msgpack-c/include/msgpack/type/set.hpp \
		msgpack-c/include/msgpack/type/string.hpp \
		msgpack-c/include/msgpack/type/vector.hpp \
		msgpack-c/include/msgpack/type/tuple.hpp \
		msgpack-c/include/msgpack/type/define.hpp \
		msgpack-c/include/msgpack/type/tr1/unordered_map.hpp \
		msgpack-c/include/msgpack/type/tr1/unordered_set.hpp \
		msgpack-c/include/msgpack/unpack.hpp \
		msgpack-c/include/msgpack/unpack.h \
		msgpack-c/include/msgpack/sbuffer.hpp \
		msgpack-c/include/msgpack/sbuffer.h \
		msgpack-c/include/msgpack/vrefbuffer.hpp \
		msgpack-c/include/msgpack/vrefbuffer.h \
		msgpack-c/include/msgpack.h \
		msgpack-c/include/msgpack/pack.h \
		msgpack-c/include/msgpack/version.h \
		../../Qt/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

