// Generated by CoffeeScript 1.7.1
this.ObjectCount = (function() {
  function ObjectCount() {
    this.currentObjectCount = {
      "String": 0
    };
  }

  ObjectCount.prototype.resetObjectCount = function() {
    return this.currentObjectCount = {
      "String": 0
    };
  };

  ObjectCount.prototype.addToCurrentObjects = function(liveObjectCount) {
    var count, objectType, _results;
    _results = [];
    for (objectType in liveObjectCount) {
      count = liveObjectCount[objectType];
      _results.push(this.currentObjectCount[objectType] = count);
    }
    return _results;
  };

  ObjectCount.prototype.timeSeries = function() {
    var count, objectType, otherCount, sortedData, top8, _ref;
    sortedData = _.sortBy(_.pairs(this.currentObjectCount), function(element) {
      return element[1];
    });
    top8 = _.object(_.last(sortedData, 8));
    otherCount = 0;
    _ref = this.currentObjectCount;
    for (objectType in _ref) {
      count = _ref[objectType];
      if (!top8[objectType]) {
        otherCount += 0;
      }
    }
    top8["Other"] = otherCount;
    return top8;
  };

  return ObjectCount;

})();
