// Generated by CoffeeScript 1.7.1
this.ObjectCount = (function() {
  function ObjectCount() {
    this.currentObjectCount = {
      "String": 0
    };
    this.otherObjects = {};
  }

  ObjectCount.prototype.resetObjectCount = function() {
    return this.currentObjectCount = {
      "String": 0
    };
  };

  ObjectCount.prototype.addToCurrentObjects = function(liveObjectCount) {
    var count, objectType, _results;
    _results = [];
    for (objectType in liveObjectCount) {
      count = liveObjectCount[objectType];
      _results.push(this.currentObjectCount[objectType] = count);
    }
    return _results;
  };

  ObjectCount.prototype.timeSeries = function() {
    var atomicData, count, finalData, objectType, otherCount, sortedData;
    sortedData = _.object(_.sortBy(_.pairs(this.currentObjectCount), function(element) {
      return element[1] * -1;
    }));
    otherCount = 0;
    atomicData = 0;
    finalData = {};
    for (objectType in sortedData) {
      count = sortedData[objectType];
      if (this.otherObjects[objectType]) {
        otherCount += count;
      } else {
        if (atomicData < 10) {
          finalData[objectType] = count;
          atomicData += 1;
        } else {
          otherCount += count;
          this.otherObjects[objectType] = true;
        }
      }
    }
    if (otherCount > 0) {
      finalData["Other"] = otherCount;
    }
    return finalData;
  };

  return ObjectCount;

})();
